language: node_js
node_js:
- '8'
cache:
  directories:
  - node_modules
script:
- npm run lint
- npm test
- npm run build
deploy:
  skip_cleanup: true
  provider: heroku
  app: gard-engen-build-and-deploy
  api_key:
    secure: JQVPDOEiffYzA99LEYr45B3vIRZb9SdB89PsiRDJ8IaHLfPQhe1eFyFoEXU/SkmDcKS25Qg1wQx7x4s6hW48xFBQU2D8MvaTm70jEaldgxXgSZ1SWJqIK/PIwtAkesCjFxLbWLf9FxuRXf2/pyaWAzaYjX2Unf2UE/8O4KIt894zphZ1BivWD5uOe+rKxU2KjB66bF46lzrWLNXgoomqBqrgMEKwnUY8Wp7UAU+2xowQgpaxjxhbfgWN9xK0RnxvRBu6SKHjvYZ0TrKLVI/8vjiedFmCy2s1W1rW9kiiygtG7UzscXSFdACKNUpwlte6JGZiT6D6jj3TQPCV/MV8udOFB0a7c9Mmf0xd2hFOcKSvcktkFM+JQmA4Z8qcyZVXGSOpKslZ5ADxcVodgoh5G/tVwqjsHhyA+FaqlHZ9LiPMn2Ec4sf2ix2GyXxIg3omVSzmvzCtq5/kk1DuQlqDk41SOSMP4p21SB6I0BGTqPd5chMD/QvfH/Qk+Mg591tyR1ZNKWaDlURq7pUkX77ecJ+Ioa2/6DCvy0AF85NUPje4CCJht9AFYGibn9gbyMYgdBoLQT/w65mNWKIYqa2kMflAPqdFBHNQRQV5rThAcZiKZFuaEfaz7hWaUVKYKhGNOSH5aBBzjZ/JbnD6IE4Ly+LWi4DL9gQTxKT2FrnoHe4=
